=== xpatmah/All_Code/basicCoding/src/main/java/com/org/java/utilities/xml/patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.maheshpathak.com/patient"
	xmlns:tns="http://www.maheshpathak.com/patient"
	elementFormDefault="qualified">

	<element name="patient" type="tns:Patient" />

	<complexType name="PaymentType">
		<choice>
			<element name="cash" type="int" />
			<element name="insurance" type="tns:Insurance" />
		</choice>
	</complexType>

	<complexType name="Insurance">
		<all>
			<element name="provider" type="string" />
			<element name="limit" type="int" />
		</all>
	</complexType>


	<complexType name="Patient">
		<sequence>
			<element name="id" type="tns:ID" />
			<element name="name" type="tns:StringChar" />
			<element name="age" type="int" />
			<element name="dob" type="date" />
			<element name="email" type="string" maxOccurs="unbounded" />
			<element name="gender" type="tns:gender" />
			<element name="phone" type="string" />
			<element name="payment" type="tns:PaymentType" />
		</sequence>
		<attribute name="xid" type="tns:ID" />
	</complexType>

	<simpleType name="ID">
		<restriction base="int">
			<pattern value="[0-9]*">
			</pattern>
		</restriction>
	</simpleType>

	<simpleType name="StringChar">
		<restriction base="string">
			<maxLength value="15" />
		</restriction>
	</simpleType>

	<simpleType name="gender">
		<restriction base="string">
			<enumeration value="M" />
			<enumeration value="F" />
		</restriction>
	</simpleType>

</schema>

=== xpatmah/All_Code/basicCoding/src/main/java/com/org/java/utilities/xml/dfjkvsdnfjk.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.maheshpathak.com/patient"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.maheshpathak.com/patient patient.xsd "
	xid="34">
	<tns:id>23</tns:id>
	<tns:name>tns:name</tns:name>
	<tns:age>0</tns:age>
	<tns:dob>2001-01-01</tns:dob>
	<tns:email>tns:email</tns:email>
	<tns:gender>M</tns:gender>
	<tns:phone>tns:phone</tns:phone>
	<tns:payment>
		<tns:insurance>
			<tns:provider>kfsdjhksdjf</tns:provider>
			<tns:limit>23</tns:limit>
		</tns:insurance>
	</tns:payment>
</tns:patient>
